name: Tests

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'prime_backup/**'
      - 'tests/**'

jobs:
  # unit_test:
  fuzzy_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        seed: ['0', '1', '2', '3', '4', '5', '6', '7']
    name: fuzzy test with random seed ${{ matrix.seed }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov -r requirements.txt -r requirements.optional.txt

      # https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#testing-with-pytest-and-pytest-cov
      - name: Run fuzzy test
        run: |
          export PYTHONPATH=$(pwd)
          python tests/test_fuzzy_run.py
        env:
          PRIME_BACKUP_FUZZY_TEST_SEED: ${{ matrix.seed }}
          PRIME_BACKUP_FUZZY_TEST_ITERATION: '1000'
